function packUnscramble(id, title, level, sentences) {
  return {
    id,
    title,
    level,
    kind: "build",
    prompt: "Tap the words in the right order. Capital first. Full stop or question mark last.",
    rounds: sentences.map((answer) => ({
      answer,
      tiles: answer.trim().split(/\s+/),
    })),
  };
}

const UNSCRAMBLE = [
  packUnscramble("u-easy-1", "Easy pack 1", "Easy", [
    "The cat sat down.",
    "A dog can run.",
    "I like the sun.",
    "Mum has a hat.",
    "Dad can hop.",
    "The pig sat.",
    "We can run.",
    "My cup is red.",
    "The ant is small.",
    "I sit on the mat.",
  ]),
  packUnscramble("u-easy-2", "Easy pack 2", "Easy", [
    "The hen can peck.",
    "Sam has a bag.",
    "The sun is hot.",
    "I can hop.",
    "A fish can swim.",
    "The bed is big.",
    "My hat is red.",
    "We had lunch.",
    "The pup hid.",
    "I see a bee.",
  ]),
  packUnscramble("u-easy-3", "Easy pack 3", "Easy", [
    "Mum packed lunch.",
    "Dad sat down.",
    "The log is wet.",
    "A bird can sing.",
    "I like milk.",
    "The pan is hot.",
    "We stop now.",
    "The cup is full.",
    "My bag is blue.",
    "The frog can jump.",
  ]),
  packUnscramble("u-easy-4", "Easy pack 4", "Easy", [
    "I read a book.",
    "She has a pen.",
    "The sky is blue.",
    "We play a game.",
    "The cake is sweet.",
    "He ran home.",
    "I pack my bag.",
    "The door is shut.",
    "We ate the pie.",
    "The lamp is on.",
  ]),
  packUnscramble("u-medium-1", "Medium pack 1", "Medium", [
    "Sam kicked the red ball.",
    "Mia ate the sweet cake.",
    "Mum read a long book.",
    "The bird sang a song.",
    "Dad cooked the fish.",
    "We packed fruit and water.",
    "I can hop on one foot.",
    "The pig sat in the mud.",
    "Where is my blue bag?",
    "What time is dinner?",
  ]),
  packUnscramble("u-medium-2", "Medium pack 2", "Medium", [
    "Who took the red pen?",
    "The tiny frog hid under a leaf.",
    "A loud bird sat on the fence.",
    "My friend went to school.",
    "They said they were going there.",
    "I wore a coat because it was cold.",
    "Sam ran and Mia jumped.",
    "It was late so we went home.",
    "The bright sun warmed the path.",
    "My soft cat slept on the bed.",
  ]),
  packUnscramble("u-medium-3", "Medium pack 3", "Medium", [
    "We had lunch in the sun.",
    "The pup hid in the bed.",
    "Can you help me please?",
    "Why is the door shut?",
    "Mum packed my red bag.",
    "I like this book because it is funny.",
    "The huge wave crashed on the sand.",
    "We went to the park after school.",
    "Grandma let me stir the cake.",
    "I ride my bike with Mum.",
  ]),
  packUnscramble("u-hard-1", "Hard pack 1", "Hard", [
    "I wanted to play but I had to do jobs.",
    "The bag was heavy but I carried it.",
    "People were happy because we won the game.",
    "I would like a cold drink please.",
    "Saturday is my favourite day of the week.",
    "The school fete was busy and fun.",
    "Making pancakes is easy if you mix well.",
    "First we mix the flour and milk.",
    "Then we cook them in a pan.",
    "I felt proud when I gave Mum the card.",
  ]),
  packUnscramble("u-hard-2", "Hard pack 2", "Hard", [
    "The library is a quiet happy place.",
    "I look for books about animals.",
    "Sometimes the librarian helps me choose.",
    "I always leave with a new story.",
    "We jumped over the cold waves at the beach.",
    "I love reading at night in my room.",
    "Our class grew beans in little cups.",
    "It was exciting to watch them grow.",
    "I remember a hot day at the beach.",
    "I felt brave when I jumped in.",
  ]),
  packUnscramble("u-hard-3", "Hard pack 3", "Hard", [
    "Rainy Saturdays can be the nicest days.",
    "We bake biscuits and then we play cards.",
    "My bike is red and shiny in the sun.",
    "We always wear our helmets on the road.",
    "The kitchen smells like sweet lemon cake.",
    "The hens lay warm brown eggs each morning.",
    "I was late because the bus was full.",
    "She said she would help me after lunch.",
    "We stayed inside because it was raining hard.",
    "I go to bed warm and full of stories.",
  ]),
];
